{{- if .Values.serviceAccount.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "frontend.fullname" . }}-multus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "frontend.fullname" . }}-multus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "frontend.fullname" . }}-multus
subjects:
  - kind: ServiceAccount
    name: {{ include "frontend.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}